language: node_js
node_js:
  - "lts/*"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsnappy-dev
cache:
  directories:
  - $HOME/data
env:
  POSTAL_DATA_DIR=~/data
  POSTAL_DOWNLOAD_DATA=1
