name: check
on: [push]
env:
  POSTAL_DATA_DIR: ${{ github.workspace }}/libpostal_data
  POSTAL_DOWNLOAD_DATA: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@main
        id: libpostal-data
        with:
          path: ${{ env.POSTAL_DATA_DIR }}
          key: libpostal-data
      - uses: actions/setup-node@main
        with:
          node-version: 'lts/*'
      - run: yarn install
      - run: make check
